version: "3.8"

services:
  image-host:
    build: ./image-host          # points to Dockerfile directory
    container_name: image-host
    ports:
      - "8420:80"                  # http://HOST_IP:8420/image.jpg
    networks: [ocr-net]

  ocr-processor:
    build: ./ocr-processor         # points to Dockerfile directory
    container_name: ocr-processor
    depends_on: [image-host]
    networks: [ocr-net]

networks:
  ocr-net:
    driver: bridge
