version: "3.8"

services:
  image-host:
    # 1) Give it a canonical image name…
    image: 4jakers18/fair_roller_image-host:latest
    # 2) …and point to your build context
    build: ./image-host
    # 3) Force “always build” instead of pull-then-build-if-missing
    pull_policy: build

    ports:
      - "8420:80"
    volumes:
      - uploads:/uploads
    networks: [ocr-net]

  ocr-processor:
    image: 4jakers18/fair_roller_ocr-processor:latest
    build: ./ocr-processor
    pull_policy: build

    depends_on:
      - image-host
    networks: [ocr-net]

networks:
  ocr-net:
    driver: bridge

volumes:
  uploads:
