version: "3.8"

services:
  image-host:
    build: ./image-host
    container_name: image-host
    ports:
      - "8420:80"                # http://<docker-host>:8420/
    volumes:
      - uploads:/uploads         # persist images
    networks: [ocr-net]
    
  ocr-processor:
    build: ./ocr-processor
    container_name: ocr-processor
    depends_on: [image-host]
    networks: [ocr-net]

networks:
  ocr-net:
    driver: bridge

volumes:
  uploads:                       # named volume lives on the Docker host

# add change to force portaner to actually update the stack lol